[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "qs"
version = "1.0"
dependencies = []
scripts.declarr = "declarr.main:main"

[tool.setuptools.package-data]
"declarr.data" = ["*.json"]
